### ISSUE TITLE
[Blitz FFA/64] TNT Rain

### ISSUE THREAD

**Issue by Diamyx** [OvercastCommunity/CommunityMaps#169] opened 2021-04-01 15:22 UTC
### Checklist

- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created a map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
TNT Rain

## Gamemode & Map Description  
arcade map where people shoot TNT on the ceiling with a flame bow which then falls and blows up the ground

## Team Sizes
any size probably works, FFA

## Screenshots
![map](https://i.imgur.com/hELQq8p.png)

# XML
https://gist.github.com/Diamyx/80035b287fc89764860c1c3dbe4a3b11

# Map Image
![map](https://user-images.githubusercontent.com/8431616/113316405-f8f06600-9316-11eb-913e-177915350212.png)

# Download Link
https://www.mediafire.com/file/z8k12813lluzpdp/TNT_Rain.zip/file

**Comment by rockymine** [comment] 2021-04-01 15:34
very creative c:

**Comment by CrazyisCreeps** [comment] 2021-07-04 19:17
Alright loaded it up and did a play test. Love the concept, but holy moly does it ever kill the fps (and the server's tps). I think part of the problem is that the TNT above can be setup by TNT that's knocked around by other exploding TNT and priming the whole ceiling of TNT to go off at once.

This map probably takes a spot in the top 5 maps to kill the server's tps 😉 Unless the lag issue can be fixed, I think this map is pretty much unplayable.

**Comment by calcastor** [comment] 2021-11-29 03:01
Not sure if the issues for this were ever resolved but would otherwise fit well in the set-next pool or fun pool. Since it's more or less unplayable I'll close the issue for now.

**Closed by calcastor** 2021-11-29 03:01 UTC
Labels: map, submission
