### ISSUE TITLE
[Bedwars/12v12v12v12] Bed Wars: Luxor

### ISSUE THREAD

**Issue by arcadeboss** [OvercastCommunity/CommunityMaps#818] opened 2023-09-20 04:29 UTC
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Bed Wars: Luxor

### Gamemode & Map Description

    An Egyptian-themed Bed Wars map for 12v12v12v12
    Pyramid has 3 separate chambers with spawners all at 0,0 for perfect emerald celestial alignment.
    At Sudden Death the 3 chambers are connected, ensuring face-to-face moments during the final seconds of games.
    Same BW for Alpha engine by arcadeboss, Cazadorian, _Pear & ElectroidFilms that "Bed Wars: Thunderbird" uses
    Takes advantage of new PGM Fireball Power functionality for Fireball Jumping, etc. - h/t cs_ & Pablete1234

![2023-09-19_22 46 14](https://github.com/OvercastCommunity/CommunityMaps/assets/3164203/cab00a78-7170-4515-a2ab-e0d193d31caf)

### Team Sizes

12v12v12v12

### Screenshots

https://imgur.com/a/GXDOfVk

### XML

https://github.com/OvercastCommunity/CommunityMaps/blob/3695786157d8f794b61616304cb5625e42e3d276/other/bedwars/luxor/map.xml

### Map Image

![map](https://github.com/OvercastCommunity/CommunityMaps/assets/3164203/d45af40c-a41d-47b4-9a82-a77272820b54)

### Map Download

https://github.com/OvercastCommunity/CommunityMaps/tree/3695786157d8f794b61616304cb5625e42e3d276/other/bedwars/luxor

Use download links

https://github.com/OvercastCommunity/CommunityMaps/pull/817

**Comment by calcastor** [comment] 2024-07-29 03:13
Closing this as it seems to play as intended for events

**Closed by calcastor** 2024-07-29 03:13 UTC
Labels: map, submission, loaded, arcade
