### ISSUE TITLE
[Arcade/30] Mega Cacti Mania

### ISSUE THREAD

**Issue by StanleyThat** [OvercastCommunity/CommunityMaps#447] opened 2022-07-29 04:56 UTC
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [x] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [x] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [x] I have created an XML file
- [x] I have created an map image
- [x] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Mega Cacti Mania

## Gamemode & Map Description  
Arcade. Epic map like cacti terror.

**What makes it different?**

- You have jump boost 4

- Smaller player count so it can be sponsored more often.

## Team Sizes
30 Players Max, FFA

## Screenshots
[Imgur](https://imgur.com/a/a8fVNur)

# XML
[XML](https://gist.github.com/zzuf-fer/31ec040f57a80216963001442c0793d1)

# Map Image
Please attempt to [make](https://pgm.dev/docs/guides/packaging/compiling-and-releasing#the-map-image) a nice `map.png` in `290x246` resolution and upload it by dragging it into this text box.
![map](https://user-images.githubusercontent.com/73564460/189515252-9b05a966-2807-4f05-9f8e-bde2690e8b30.png)

# Download Link
[Dropbox](https://www.dropbox.com/s/mbbi2dj9wckt4ax/Mega_Cacti_Mania_1.2.0.zip?dl=0)

**Comment by Cazadorian** [comment] 2022-07-30 20:26
Please rename this map to something more serious before we load it.

**Comment by StanleyThat** [comment] 2022-07-31 22:54
fixed.

**Comment by calcastor** [comment] 2022-07-31 22:56
> fixed.

no, try again.

**Comment by StanleyThat** [comment] 2022-07-31 23:18
was worth a shot! 😏

**Comment by Cazadorian** [comment] 2022-08-03 17:31
The map has significant XML errors and even after fixing them enough to get the map to load, large parts of the map do not function and it is hard to tell how a lot of it is even meant to function. Please update the map to fix these issues and ensure the map is fully working as intended before you update this issue with the new files.

**Comment by StanleyThat** [comment] 2022-08-20 11:05
I dont have time to work on this right now, but when I do I will just reupload everything, but I'll close it for now.

**Comment by StanleyThat** [comment] 2022-09-11 06:27
Update:
Fixed errors, retested, & Improved the map building

**Comment by StanleyThat** [comment] 2022-09-11 08:04
Update again:
Fixed death on start

**Comment by zzuf-fer** [comment] 2022-09-11 15:58
Please utilize [this updated XML file](https://github.com/zzuf-fer/zzuf/blob/24e86428eb07f69299b4609f4ecebe5253b756ea/map.xml) instead.

With these settings, I have only seen the death screen thing happen once during the very first test, and then never again for the remainder of the test session. Even then, this time you could actually click on the Respawn button and it would just close that message and continue the game as normal.

**Comment by StanleyThat** [comment] 2022-09-11 23:44
I've added the code above now

**Comment by Cazadorian** [comment] 2022-09-30 11:32
From what I've seen of the map play in its current form it just feels like a lesser version of the other Cacti maps without much going for it specifically, simply having jump boost doesn't really cut it. The map likely needs some kind of change made to make it stand out, which is up to you to decide on and implement.

**Comment by StanleyThat** [comment] 2022-10-01 09:00
> From what I've seen of the map play in its current form it just feels like a lesser version of the other Cacti maps without much going for it specifically, simply having jump boost doesn't really cut it. The map likely needs some kind of change made to make it stand out, which is up to you to decide on and implement.

We have just updated the map, increasing the jump boost to something much higher as we feel like it will make the game more interesting. Also, we reduced the time and added a border.

We would like to test these changes to see if it's enough. If not could try something else.

**Comment by zzuf-fer** [comment] 2022-10-01 16:59
Please include ``safe="true"`` in the <spawns> module, as there is a small one block wide gap in middle now. I had that in my local files but apparently hadn't copied it over to the gist in time. Sorry about that.

**Comment by Cazadorian** [comment] 2022-11-13 04:08
After seeing the current version play a lot more I still think the map needs a lot more work. This map in its current form still feels rather subpar, and as one person put it "It just feels like someone removed the falling blocks from that other Cacti map and turned on a /mutation". 

My personal suggestion to make the map stand out more would be to modify the arena itself a lot more. If you wish to keep using the high potency jump boost you could expand the arena in size and add more verticality to it rather than just a flat rectangle, by adding floating platforms and potential parkour elements between them. What you do to make the map stand out more its ultimately on you to decide however.

**Comment by calcastor** [comment] 2023-05-06 17:26
This seems to get played infrequently during Friday events. However, as it's been six months since any further commenting on it, I am going to close this issue. At the moment there is no harm in it being loaded, but ideally this would be made more unique like Caz's comment suggests.

**Closed by calcastor** 2023-05-06 17:26 UTC
Labels: map, submission, loaded
