### ISSUE TITLE
[Blitz/50v3] Hide n' Seek: Clue

### ISSUE THREAD

**Issue by CredensJustitiam** [OvercastCommunity/CommunityMaps#160] opened 2021-03-20 03:16 UTC
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created a map image
- [X] I have uploaded the map zip file to a file sharing service
- [x] The map has been tested locally to make sure it works

# Map Name
Hide n' Seek: Clue

## Gamemode & Map Description  
(Arcade/Blitz) This map is spiritual successor to Crazy_'s Hide n' Seek that takes place in a Clue-themed mansion. It plays differently from the original Hide n' Seek, as the map's design is much more confined. Utilizing secret passageways and continually changing your hiding spot when no one is looking is key to survival on this map. There are also some hidden items around the map for the hiders to use, although they could only buy a few seconds for the hiders at most, so they must be used strategically in order to be effective.

## Team Sizes
The two teams are the "Hiders" and "Seekers". They work exactly the same as in Crazy_'s Hide n' Seek, with there traditionally being 1 seeker for every ~16 hiders.

## Screenshots
https://imgur.com/gallery/H1aT4ZF

# XML
https://gist.github.com/CredensJustitiam/b6018d049f2137a56ced97d88f6be6eb

# Map Image
![map](https://user-images.githubusercontent.com/80809061/111730512-d3e7f780-882e-11eb-897d-ecae1d4355fb.png)

# Download Link
https://www.mediafire.com/file/7u8651gzwipijep/Hide_n%2527_Seek_-_Clue.zip/file

**Comment by calcastor** [comment] 2021-03-20 04:37
Just loaded this on a local test server, seems there's some things that need to be fixed in the XML:

Line 26: the enchantment should be "aqua_affinity"
Line 115: need to specify wood button or stone button
Line 116: cobweb should be "web"

I changed these to get it to load for my test but wasn't able to properly play it through and of course I don't know whether or not you meant the wood or stone button, but beyond these small errors it worked 100% from what I could tell. Hope it can be play tested on OCC soon!

**Comment by CredensJustitiam** [comment] 2021-03-20 05:00
Glad you liked it! Thanks for pointing those errors out, I just updated the xml file to fix them. Also, this is supposed to be a 50v3 map, so just disregard the title.

**Comment by CrazyisCreeps** [comment] 2021-03-20 05:39
Alright so.

I have a big concern. This map appears to be (https://www.planetminecraft.com/project/clue-mansion/), a map which was originally posted to Planet Minecraft July 24th, 2019, and then later updated and completed with a download September 25th, 2020. I think in a message sent by a Alina Gray in our discord, they mentioned making this map for another server about a year ago. 

I think the map looks awesome, but we take claiming work that isn't one's own as their own quite seriously, so I hope you can understand my caution with this situation. I got a couple questions that I hope can sort this out.

1. Did you/Alina Gray make this map?
2. Who's Alina Gray in relative to you? Is this you or are you the friend?
3. At the map's observer spawn, you give credits to a Internet_Bowser and a archenswag9001. Who are these people?

**Comment by CredensJustitiam** [comment] 2021-03-20 21:11
I'm Alina Gray on Discord, Internet_Bowser is my friend who helped with the map
and archenswag9001 is my sister who helped me with the xml stuff. I need to admit,
we used the original map from Planet Minecraft as a template and then made changes
on our own to better suit the server we were making it for. If you compare the
maps, you will find there are a lot of differences, so we didn't straight up copy
their map.

I messaged the original creator when I started updating the map but he seems to be
completely inactive online. If he responds and says it's okay to use the map, I'll
credit him and reupload the map if that's okay.

**Comment by technodono** [comment] 2021-03-20 23:29
If he's inactive maybe you shouldn't use the map... I mean alot of the fun in map-making is being able to create your own map and say: Hey! my builds are really cool or "I love this map... looks great"... I'm just a mapmaker though so IDK if that applies

**Comment by technodono** [comment] 2021-03-20 23:31
if you do end up making a new map from scratch i recommend using stratus anax... it's an easy 1.8.9 server for building maps like mine :) hope this helps

**Comment by CredensJustitiam** [comment] 2021-03-20 23:36
Update: I just contacted him on Reddit and he said he's okay with the map being used. I updated the map files so he's entirely credited with the creation of the map. This has been a wild 24 hours but I'm so glad this is over.

**Comment by CrazyisCreeps** [comment] 2021-03-21 02:21
Alright I appreciate your honesty and your actions in regards to this situation. If it's alright with you, do you mind taking a screenshot of the conversation you had on Reddit with the author and either posting it here, or sending it to me in discord (Crazy#1675). Thanks.

**Comment by CredensJustitiam** [comment] 2021-03-21 02:42
Alright, I sent it in discord

**Comment by CrazyisCreeps** [comment] 2021-03-21 03:59
Cool, thanks for sending me that. It looks like an awesome map, and it's great that we now have author permission to be able to use the map as yours.

Right off the bat, I noticed there were some command blocks on the map that were doing cool things, like giving speed in specific regions. Command blocks are unfortunately disabled on our server, but you can reproduce actions like giving speed in specific regions through the XML. The other command blocks were honestly too complex for me to understand what's going on, but let me know and I can try to help you figure out how, if possible, it can be done through the XML.

**Comment by CredensJustitiam** [comment] 2021-03-21 04:18
The only command blocks that matter are the ones that give speed in certain areas. I just need 4 that give speed VI in certain locations and 4 that remove that speed in different locations. Can you give me a template for what those lines should look like in xml?

**Comment by CrazyisCreeps** [comment] 2021-03-22 08:45
Something like this would do the trick https://gist.github.com/CrazyisCreeps/06509f8cb3747035c96c43c7ecb6a22b

**Comment by CredensJustitiam** [comment] 2021-03-22 10:00
Thanks, I updated the files again. I think it should work now?

**Comment by CrazyisCreeps** [comment] 2021-04-01 05:29
Alright so here's your map xml, fixed up to the point to allow it to load properly. I also credited the authors in obs spawn in the xml, but want to ensure the guy from planetmc is also credited. Do you know his username?

Secondly there's a chest in the basement area that seems to crash client when they open it. I have no idea what the item in the chest is, but if you could remove that or something that would be super appreciated.

Once that's fixed up, I'll load it up and see how it plays

**Comment by CredensJustitiam** [comment] 2021-04-01 20:30
BlanchePanda is the person from planetmc who made the map, so the new xml is correct.

I tried to fix the chest in the basement, so let me know if it works now. If it doesn't work, I put some temporary chests in the main hall, and I would appreciate it if you could let me know which ones work and which ones don't.

Also, one of the brewing stands in the kitchen might crash the game, so those should be checked too if you haven't already.

**Comment by CrazyisCreeps** [comment] 2021-04-03 05:18
This is something I need you to check and ensure that they all work. If you suspect their are more containers that will crash clients, please fix it.

I double checked the chests in question, and they still crash my client. While I was at it, yes, I checked the kitchen and those crash me as well.

You also have command blocks/chests in the main foyer that are new since you last updated the world file. I assume those aren't meant to be there.

For reference, these 6 chests on the right are the ones in question that I had found. But seriously, take a look at all containers and ensure they won't crash clients.
![2021-04-03_01 14 29](https://user-images.githubusercontent.com/7937351/113469280-63d69580-941a-11eb-8b15-6612a16ab344.png)

**Comment by CredensJustitiam** [comment] 2021-04-03 06:27
Thanks for helping with this, I believe it will work now. I previously put custom potions into the chests that I gave myself via command blocks, but for some reason the client couldn't support those. I replaced everything with vanilla potions that don't rely on the command, so everything should be fixed.

**Comment by CrazyisCreeps** [comment] 2021-04-07 06:40
Alright I loaded it up for testing.

**Comment by CrazyisCreeps** [comment] 2021-04-07 23:04
You'll notice I updated the xml to ensure players spawn in adventure mode. This fixes players doing stuff like to hide https://cdn.discordapp.com/attachments/708765797694046228/829489455706013756/unknown.png

**Comment by CredensJustitiam** [comment] 2021-04-08 01:06
Ok, that's good. Also, I checked the map file I uploaded and there's no hole in that one wall that let people get out of the map, so I'm not sure how that hole got there during testing. Either the client removes those blocks for some reason or an admin accidentally edited the map, idk

**Comment by CrazyisCreeps** [comment] 2021-04-08 01:27
I heard some blocks being broken during that last map test so that seems extremely likely

**Comment by applenick** [comment] 2021-04-08 01:30
Um, oops

**Comment by CredensJustitiam** [comment] 2021-04-09 20:38
I updated the map with added barriers because people were able to glitch under some iron trapdoors using buttons

**Closed** 2021-07-29 04:40 UTC
Labels: map, submission
